---
- name: geoip2
  src: https://github.com/cisagov/ansible-role-geoip2
  version: lineage/skeleton
- name: pip
  src: https://github.com/cisagov/ansible-role-pip
- name: python
  src: https://github.com/cisagov/ansible-role-python
- name: upgrade
  src: https://github.com/cisagov/ansible-role-upgrade
